[server]
port=":80"

#[server.ssl]
#key=""
#cert=""

#[session]
#secret=""
#duration=""

[database]
driver="sqlite3"
datasource="/data/drone.db"

#[registration]
#open=true

[github]
client=""
secret=""

#[github_enterprise]
#client=""
#secret=""
#api=""
#url=""
#private_mode=false
#
#[bitbucket]
#client=""
#secret=""
#
#[gitlab]
#url=""
#
#[smtp]
#host=""
#port=""
#from=""
#user=""
#pass=""

[worker]
nodes=[
    "unix:///var/run/docker.sock",
    "unix:///var/run/docker.sock"
]
